### ISSUE TITLE
'sourcemap' vs 'source-map'

### ISSUE THREAD

**Issue by tribou** [diegohaz/webpack-blocks-server-source-map#2]
According to the [webpack devtool docs](https://webpack.js.org/configuration/devtool/), there is a `source-map` option, but not a `sourcemap`.  Did you mean to put `source-map` as the server devtool option?

**Comment by diegohaz** [comment]
It works either way. Maybe we should change the default to `source-map` and accept a `devtool` argument so user can set it to another value. Would you mind to send a PR?
